services:
  backend:
    container_name: assistant_photo_backend_service
    image: maliciamrg/assistant_photo_backend:latest
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - ASSISTANT_ROOTPATH=/Photo/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/photosdb
      - SPRING_DATASOURCE_USERNAME=photos_user
      - SPRING_DATASOURCE_PASSWORD=photos_pass
    ports:
      - "8999:8099"
    volumes:
      - '/Photo/70_Catalog_Phototheque:/Lrcat'
      - '/Photo:/Photo'
    depends_on:
      - redis
      - postgres
    networks:
      - assistant-photo

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Expose Redis port 6379 to the host
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - assistant-photo

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: photosdb
      POSTGRES_USER: photos_user
      POSTGRES_PASSWORD: photos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - assistant-photo

networks:
  assistant-photo:

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
