services:
  backend:
    container_name: assistant_photo_backend_service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - ASSISTANT_ROOTPATH=/Photo/
    ports:
      - "8999:8099"
    volumes:
      - '/Photo/70_Catalog_Phototheque:/Lrcat'
      - '/Photo:/Photo'
    depends_on:
      - redis
    networks:
      - assistant-photo

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Expose Redis port 6379 to the host
    volumes:
      - redis_data:/data  # Persist Redis data on the host machine
    restart: always
    networks:
      - assistant-photo

networks:
  assistant-photo:

volumes:
  redis_data:
    driver: local