assistant:
  rootPath: Y:\
  dryRun: false
management:
  health:
    redis:
      enabled: false

logging:
  level:
#    org.springdoc: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.data.redis: DEBUG
#    org.springframework.cache: DEBUG
#    org.springframework.data.redis.cache.RedisCache: TRACE
    com.malicia.mrg.assistant.photo: debug
    root: info


