spring:
  application:
    name: AssistantPhoto
  datasource:
    url: jdbc:postgresql://localhost:5932/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Can be "update", "create", or "validate" for development
    show-sql: true      # Enable showing SQL in logs
    properties:
      hibernate:
        format_sql: true  # Format SQL queries for readability
  sql:
    init:
      mode: always       # Initialize schema on startup (optional)
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
#      password: yourpassword  # Optional, if your Redis instance requires authentication
      timeout: 2000  # Optional timeout in milliseconds

application:
  version: "@project.version@"
  ipWan: '192.212.5.200'
server:
  port: 8099
logging:
  level:
    org:
      springdoc: DEBUG
springdoc:
  show-actuator: true

my:
  app:
    name: AssistantPhoto
    version: "1.0"
assistant:
  dryRun: true
  name: assistant
  rootPath: ./backend/src/test/resources/
  fileExtensionsToWorkWith:
    - jpg
    - tif
    - tiff
    - dng
    - jpeg
    - arw
    - mp4
    - png
    - mts
    - mov
    - avi
    - m2ts
    - 3gp
    - m4v
    - mpg
    - psd
    - bmp
    - gif
    - tiff_original
  groupPhoto:
    ecartEnMinutes: 20
    photoMin: 5
  seanceType:
    - nom: all_in
    - nom: Assistant_Work
    - nom: Rejet
    - nom: Sauvegarde
    - nom: Events
      uniteDeJour: 1
      nbMaxParUniteDeJour: 15
      ratioStarMax:
        - 25
        - 12
        - 5
        - 2
        - 1
      zoneValeurAdmise:
        - £DATE£
        - "@00_EVENT@"
        - "@00_WHERE@"
        - "@00_WHAT@|@00_WHO@"
      rapprochementNewOk: true
    - nom: Holidays
      uniteDeJour: 7
      nbMaxParUniteDeJour: 30
      ratioStarMax:
        - 25
        - 12
        - 5
        - 2
        - 1
      zoneValeurAdmise:
        - £DATE£
        - "@00_EVENT@"
        - "@00_WHERE@"
        - "@00_WHAT@|@00_WHO@"
      rapprochementNewOk: true
    - nom: Shooting
      uniteDeJour: 1
      nbMaxParUniteDeJour: 5
      ratioStarMax:
        - 25
        - 12
        - 5
        - 2
        - 1
      zoneValeurAdmise:
        - £DATE£
        - "@00_PHOTOGRAPHY@"
        - "@00_WHERE@"
        - "@00_WHAT@|@00_WHO@"
      rapprochementNewOk: true
  repertoireOfType:
    - seanceType: all_in
      repertoire:
        - path: "00-CheckIn"
          description: "Main check-in folder"
    - seanceType: assistant_work
      repertoire:
        - path: "10-Assistant_work"
          description: "Work folder for the Assistant"
    - seanceType: Events
      repertoire:
        - path: "50-Phototheque\\##Events 10-15 j"
          description: "Events photographs"
    - seanceType: Holidays
      repertoire:
        - path: "50-Phototheque\\##Holidays 20-30 sem"
          description: "Holiday photographs"
    - seanceType: Shooting
      repertoire:
        - path: "50-Phototheque\\##Shooting 03-05 j"
          description: "Shooting session photographs"
    - seanceType: Rejet
      repertoire:
        - path: "99-Rejet"
          description: "Rejected items"
    - seanceType: Sauvegarde
      repertoire:
        - path: "50-Phototheque\\#Sauvegarde 999 j"
          description: "Backup photographs"
info:
  application:
    name: ${spring.application.name}
    version: ${application.version}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,openapi,swagger-ui
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true

